# Generated by Django 4.0.6 on 2022-07-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.TimeField(),
        ),
    ]
