# Generated by Django 4.0.6 on 2022-07-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to=''),
        ),
    ]
